## Checks PR is opened by Renovate
name: Renovate

on:
    pull_request:
      types: [opened, reopened]
      branches:
        - renovate/**

jobs:
  Validate-Gradle:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: ./.github/actions/setup
        with:
          encryption_key: ${{ secrets.GRADLE_ENCRYPTION_KEY }}
      - name: Gradle Wrapper Validation
        uses: gradle/actions/wrapper-validation@94baf225fe0a508e581a564467443d0e2379123b # v4

  DependencyGuard:
    runs-on: ubuntu-latest
    needs: [ Validate-Gradle ]
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: ./.github/actions/setup
        with:
          encryption_key: ${{ secrets.GRADLE_ENCRYPTION_KEY }}
      - name: Build
        run: ./gradlew dependencyGuardBaseline


  Commit-changes:
    runs-on: ubuntu-latest
    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write
    needs: [ DependencyGuard ]
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: ./.github/actions/setup
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_options: '--amend'
          push_options: '--force'
