# Checks PR is opened by Renovate
name: Renovate

on:
  pull_request:
    types: [opened, reopened]
    branches:
      - main

jobs:
  DependencyGuard:
    if: "startsWith(github.head_ref, 'renovate/')"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: ./.github/actions/setup
        with:
          encryption_key: ${{ secrets.GRADLE_ENCRYPTION_KEY }}
      - name: Build
        run: ./gradlew dependencyGuardBaseline
      - uses: stefanzweifel/git-auto-commit-action@e348103e9026cc0eee72ae06630dbe30c8bf7a79 # v5
        with:
          commit_options: "--amend"
          push_options: "--force"
